title: dblock.org
locale: en_US
url: https://www.dblock.org
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
kramdown:
  input: GFM
owner:
  name: Daniel Doubrovkine
  avatar: blog.gif
  bio:
  email: dblock@dblock.org
  disqus-shortname:
  twitter: dblockdotorg
  facebook:
  google:
    plus:
    analytics: UA-4756101-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github:
  stackoverflow:
  linkedin:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
google_custom_search:
